# url is currently only used only for the RSS feed in feed.xml
url: http://br-lemes.github.io

# baseurl will often be '', but for a project page on gh-pages, it needs to
# be the project name.
# *** IMPORTANT: If your local "jekyll serve" throws errors change this to '' or
#     run it like so: jekyll serve --baseurl=''
baseurl: '/jekyll-insane'

# This can be '' to hide the Github nav button
github: 'br-lemes/jekyll-insane'

# Set this to your UA-# value, or '' to disable the block completely
gaaccount: ''

# Set this to your disqus shortname to enable comments.
disqus: 'br-lemes'

permalink: /:year/:month/:title/
paginate: 5

exclude: ['README.md', 'LICENSE']

excerpt_separator: '<!-- more -->'

default_paneltype: success

defaults:
  -
    values:
      comments: true
      lang: en

gems:
  - jekyll-paginate
  - jekyll-sitemap
